GET http://localhost:1337/validate

###

POST http://localhost:1337/addBlock
Content-Type: application/json

{
    "user": "John Doe",
    "course": "Sparka-boll-kunskap 3" 
}

###

POST http://localhost:1337/addBlock
Content-Type: application/json

{
    "user": "Kalle Persson",
    "kurs": "Sparka-boll-kunskap 1" 
}